---
dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

script:
  - ./build.sh

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: zeroc-ice-*/dist/zeroc*
  skip_cleanup: true
  on:
    tags: true
